DROP TABLE IF EXISTS Cidade;
DROP TABLE IF EXISTS Localidade;
DROP TABLE IF EXISTS EstadoCivil;
DROP TABLE IF EXISTS Pessoa;
DROP TABLE IF EXISTS Aluno;
DROP TABLE IF EXISTS Instrutor;
DROP TABLE IF EXISTS Aula;
DROP TABLE IF EXISTS Teórica;
DROP TABLE IF EXISTS Prática;
DROP TABLE IF EXISTS TipoVeículo;
DROP TABLE IF EXISTS Modelo;
DROP TABLE IF EXISTS Marca;
DROP TABLE IF EXISTS Veículo;
DROP TABLE IF EXISTS AlunoAula;
DROP TABLE IF EXISTS InstrutorTipoVeículo;

PRAGMA foreign_keys = ON;


CREATE TABLE Cidade (
	idCidade        INTEGER PRIMARY KEY AUTOINCREMENT,
	nome 			NVARCHAR2(20) NOT NULL
);

CREATE TABLE Localidade (
	idLocalidade      	INTEGER PRIMARY KEY AUTOINCREMENT,
	nome 				NVARCHAR2(20) NOT NULL,
	códigoPostal		NVARCHAR2(10),
	idCidade 				INTEGER,
	FOREIGN KEY(idCidade) REFERENCES Cidade(idCidade) 
		ON DELETE SET NULL
		ON UPDATE CASCADE 
);


CREATE TABLE EstadoCivil(
	idEstadoCivil       INTEGER PRIMARY KEY AUTOINCREMENT,
	nome 				NVARCHAR2(20) NOT NULL
);

CREATE TABLE Pessoa (
	idPessoa        INTEGER PRIMARY KEY AUTOINCREMENT,
	nome 			NVARCHAR2(50) NOT NULL,
	morada			NVARCHAR2(50),
	BI				NVARCHAR2(20),
	dataNascimento  DATE,
	idEstadoCivil     INTEGER,
	idLocalidade 		INTEGER,
	tipo 			NVARCHAR2(20) NOT NULL,
	FOREIGN KEY(idEstadoCivil) REFERENCES EstadoCivil(idEstadoCivil)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY(idLocalidade) REFERENCES Localidade(idLocalidade)
		ON DELETE SET NULL
		ON UPDATE CASCADE 
);

CREATE TABLE TipoVeículo (
	idTipoVeículo       INTEGER PRIMARY KEY AUTOINCREMENT,
	nome 				NVARCHAR2(10) NOT NULL
);

CREATE TABLE Aluno (
	idPessoa			INTEGER PRIMARY KEY AUTOINCREMENT,
	códigoAluno			INTEGER,
	idTipoVeículo		INTEGER,
	FOREIGN KEY(idTipoVeículo) REFERENCES TipoVeículo(idTipoVeículo)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY(idPessoa) REFERENCES Pessoa(idPessoa)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE Instrutor (
	idPessoa			INTEGER PRIMARY KEY AUTOINCREMENT,
	salário				INTEGER,
	tempoLecionar		INTEGER,
	FOREIGN KEY(idPessoa) REFERENCES Pessoa(idPessoa)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE Aula (
	idAula       	INTEGER PRIMARY KEY AUTOINCREMENT,
	Sumário			NVARCHAR2(20),
	Data 			DATE,
	HoraInício		TIME,
	HoraFim 		TIME,
	tipo 			NVARCHAR2(10) NOT NULL,
	idInstrutor		INTEGER,
	FOREIGN KEY(idInstrutor) REFERENCES Instrutor(idPessoa)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE Prática(
	idAula			INTEGER PRIMARY KEY AUTOINCREMENT,
	idVeículo 		INTEGER,
	FOREIGN KEY(idVeículo) REFERENCES Veículo(idVeículo)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY(idAula) REFERENCES Aula(idAula)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE Teórica (
	idAula			INTEGER PRIMARY KEY AUTOINCREMENT,
	numeroAlunos	INTEGER NOT NULL,
	FOREIGN KEY(idAula) REFERENCES Aula(idAula)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE Marca (
	idMarca		INTEGER PRIMARY KEY AUTOINCREMENT,
	nome		NVARCHAR2(20) NOT NULL
);

CREATE TABLE Modelo (
	idModelo        INTEGER PRIMARY KEY AUTOINCREMENT,
	nome 			NVARCHAR2(20) NOT NULL,
	peso 			INTEGER,
	cilindrada		INTEGER,
	potência 		INTEGER,
	velocidadeMáxima INTEGER,
	idMarca 			INTEGER,
	FOREIGN KEY(idMarca) REFERENCES Marca(idMarca)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE Veículo (
	idVeículo       INTEGER PRIMARY KEY AUTOINCREMENT,
	matrícula 		NVARCHAR2(20) NOT NULL,
	idModelo 			INTEGER,
	idTipoVeículo		INTEGER,
	FOREIGN KEY(idModelo) REFERENCES Modelo(idModelo)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY(idTipoVeículo) REFERENCES TipoVeículo(idTipoVeículo)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE AlunoAula (
	idAluno INTEGER,
	idAula INTEGER,
	PRIMARY KEY (idAluno,idAula),
	FOREIGN KEY(idAluno) REFERENCES Aluno(idPessoa)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY(idAula) REFERENCES Aula(idAula)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE InstrutorTipoVeículo (
	idInstrutor INTEGER,
	idTipoVeículo INTEGER,
	PRIMARY KEY (idInstrutor, idTipoVeículo),
	FOREIGN KEY(idInstrutor) REFERENCES Instrutor(idPessoa)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY(idTipoVeículo) REFERENCES TipoVeículo(idTipoVeículo)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);